#!/bin/bash

# Start running porgrams and services
startup

# Create user account
if [ -n "$USER" ]; then
   if [ -z "$USER_HOME" ]; then
      export USER_HOME=/gpfs01/bethge/home/$USER
   fi

   if [ -n "$USER_ENCRYPTED_PASSWORD" ]; then
      useradd -M -d $USER_HOME -p $USER_ENCRYPYTED_PASSWORD $USER
   else
      useradd -M -d $USER_HOME $USER
   fi

   usermod -u $USER_ID $USER
   adduser $USER sudo
   adduser $USER bethgelab
   adduser $USER cin
   chsh -s /bin/bash $USER
   su $USER
fi

# redirect working directory to user_home
cd $USER_HOME

# do nothing forever, so container keeps running
jupyter notebook --ip=0.0.0.0 --no-browser
